export const countries = [
  { name: "Estados Unidos", flag: "🇺🇸", image: "/placeholder.svg?height=200&width=300" },
  { name: "Canadá", flag: "🇨🇦", image: "/placeholder.svg?height=200&width=300" },
  { name: "España", flag: "🇪🇸", image: "/placeholder.svg?height=200&width=300" },
  { name: "Francia", flag: "🇫🇷", image: "/placeholder.svg?height=200&width=300" },
  { name: "Italia", flag: "🇮🇹", image: "/placeholder.svg?height=200&width=300" },
  { name: "Reino Unido", flag: "🇬🇧", image: "/placeholder.svg?height=200&width=300" },
  { name: "Alemania", flag: "🇩🇪", image: "/placeholder.svg?height=200&width=300" },
  { name: "Australia", flag: "🇦🇺", image: "/placeholder.svg?height=200&width=300" },
  { name: "Japón", flag: "🇯🇵", image: "/placeholder.svg?height=200&width=300" },
  { name: "Brasil", flag: "🇧🇷", image: "/placeholder.svg?height=200&width=300" },
  { name: "Nueva Zelanda", flag: "🇳🇿", image: "/placeholder.svg?height=200&width=300" },
  { name: "Corea del Sur", flag: "🇰🇷", image: "/placeholder.svg?height=200&width=300" },
  { name: "Irlanda", flag: "🇮🇪", image: "/placeholder.svg?height=200&width=300" },
  { name: "Noruega", flag: "🇳🇴", image: "/placeholder.svg?height=200&width=300" },
  { name: "Suecia", flag: "🇸🇪", image: "/placeholder.svg?height=200&width=300" },
  { name: "Dinamarca", flag: "🇩🇰", image: "/placeholder.svg?height=200&width=300" },
  { name: "Finlandia", flag: "🇫🇮", image: "/placeholder.svg?height=200&width=300" },
  { name: "Chile", flag: "🇨🇱", image: "/placeholder.svg?height=200&width=300" },
  { name: "Argentina", flag: "🇦🇷", image: "/placeholder.svg?height=200&width=300" },
  { name: "Portugal", flag: "🇵🇹", image: "/placeholder.svg?height=200&width=300" },
  { name: "México", flag: "🇲🇽", image: "/placeholder.svg?height=200&width=300" },
  { name: "Países Bajos", flag: "🇳🇱", image: "/placeholder.svg?height=200&width=300" },
  { name: "Suiza", flag: "🇨🇭", image: "/placeholder.svg?height=200&width=300" },
  { name: "Bélgica", flag: "🇧🇪", image: "/placeholder.svg?height=200&width=300" }
]