export const countries = [
  { name: "Estados Unidos", flag: "🇺🇸", image: "/countries/USA.webp?height=200&width=300" },
  { name: "Canadá", flag: "🇨🇦", image: "/countries/Canada.webp?height=200&width=300" },
  { name: "España", flag: "🇪🇸", image: "/countries/Espana.webp?height=200&width=300" },
  { name: "Francia", flag: "🇫🇷", image: "/countries/Francia.webp?height=200&width=300" },
  { name: "Italia", flag: "🇮🇹", image: "/countries/Italia.webp?height=200&width=300" },
  { name: "Reino Unido", flag: "🇬🇧", image: "/countries/Reino-Unido.webp?height=200&width=300" },
  { name: "Alemania", flag: "🇩🇪", image: "/countries/Alemania.webp?height=200&width=300" },
  { name: "Australia", flag: "🇦🇺", image: "/countries/Australia.webp?height=200&width=300" },
  { name: "Japón", flag: "🇯🇵", image: "/countries/Japon.webp?height=200&width=300" },
  { name: "Brasil", flag: "🇧🇷", image: "/countries/Brasil.webp?height=200&width=300" },
  { name: "Nueva Zelanda", flag: "🇳🇿", image: "/countries/Nueva-Zelanda.webp?height=200&width=300" },
  { name: "Corea del Sur", flag: "🇰🇷", image: "/countries/Corea-del-Sur.webp?height=200&width=300" },
  { name: "Irlanda", flag: "🇮🇪", image: "/countries/Irlanda.webp?height=200&width=300" },
  { name: "Noruega", flag: "🇳🇴", image: "/countries/Noruega.webp?height=200&width=300" },
  { name: "Suecia", flag: "🇸🇪", image: "/countries/Suecia.webp?height=200&width=300" },
  { name: "Dinamarca", flag: "🇩🇰", image: "/countries/Dinamarca.webp?height=200&width=300" },
  { name: "Finlandia", flag: "🇫🇮", image: "/countries/Finlandia.webp?height=200&width=300" },
  { name: "Chile", flag: "🇨🇱", image: "/countries/Chile.webp?height=200&width=300" },
  { name: "Argentina", flag: "🇦🇷", image: "/countries/Argentina.webp?height=200&width=300" },
  { name: "Portugal", flag: "🇵🇹", image: "/countries/Portugal.webp?height=200&width=300" },
  { name: "México", flag: "🇲🇽", image: "/countries/Mexico.webp?height=200&width=300" },
  { name: "Países Bajos", flag: "🇳🇱", image: "/countries/Paises-Bajos.webp?height=200&width=300" },
  { name: "Suiza", flag: "🇨🇭", image: "/countries/Suiza.webp?height=200&width=300" },
  { name: "Bélgica", flag: "🇧🇪", image: "/countries/Belgica.webp?height=200&width=300" }
]