export const countries = [
  { name: "Estados Unidos", flag: "🇺🇸", image: "/countries/USA.png?height=200&width=300" },
  { name: "Canadá", flag: "🇨🇦", image: "/countries/Canada.png?height=200&width=300" },
  { name: "España", flag: "🇪🇸", image: "/countries/Espana.png?height=200&width=300" },
  { name: "Francia", flag: "🇫🇷", image: "/countries/Francia.png?height=200&width=300" },
  { name: "Italia", flag: "🇮🇹", image: "/countries/Italia.png?height=200&width=300" },
  { name: "Reino Unido", flag: "🇬🇧", image: "/countries/Reino-Unido.png?height=200&width=300" },
  { name: "Alemania", flag: "🇩🇪", image: "/countries/Alemania.png?height=200&width=300" },
  { name: "Australia", flag: "🇦🇺", image: "/countries/Australia.png?height=200&width=300" },
  { name: "Japón", flag: "🇯🇵", image: "/countries/Japon.png?height=200&width=300" },
  { name: "Brasil", flag: "🇧🇷", image: "/countries/Brasil.png?height=200&width=300" },
  { name: "Nueva Zelanda", flag: "🇳🇿", image: "/countries/Nueva-Zelanda.png?height=200&width=300" },
  { name: "Corea del Sur", flag: "🇰🇷", image: "/countries/Corea-del-Sur.png?height=200&width=300" },
  { name: "Irlanda", flag: "🇮🇪", image: "/countries/Irlanda.png?height=200&width=300" },
  { name: "Noruega", flag: "🇳🇴", image: "/countries/Noruega.png?height=200&width=300" },
  { name: "Suecia", flag: "🇸🇪", image: "/countries/Suecia.png?height=200&width=300" },
  { name: "Dinamarca", flag: "🇩🇰", image: "/countries/Dinamarca.png?height=200&width=300" },
  { name: "Finlandia", flag: "🇫🇮", image: "/countries/Finlandia.png?height=200&width=300" },
  { name: "Chile", flag: "🇨🇱", image: "/countries/Chile.png?height=200&width=300" },
  { name: "Argentina", flag: "🇦🇷", image: "/countries/Argentina.png?height=200&width=300" },
  { name: "Portugal", flag: "🇵🇹", image: "/countries/Portugal.png?height=200&width=300" },
  { name: "México", flag: "🇲🇽", image: "/countries/Mexico.png?height=200&width=300" },
  { name: "Países Bajos", flag: "🇳🇱", image: "/countries/Paises-Bajos.png?height=200&width=300" },
  { name: "Suiza", flag: "🇨🇭", image: "/countries/Suiza.png?height=200&width=300" },
  { name: "Bélgica", flag: "🇧🇪", image: "/countries/Belgica.png?height=200&width=300" }
]